version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-28
      #- image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run: sdkmanager --licenses
      - run: yes | sdkmanager --update || exit 0
      - run:
          command: ./gradlew androidDependencies
          when: always

      - run:
          name: Analyze on SonarCloud
          command: ./gradlew build sonarqube

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
