version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    resource_class: medium
    environment:
      JVM_OPTS: -Xmx5000m
    steps:
      - checkout

      - run:
          name: Analyze on SonarCloud
          command: ./gradlew build sonarqube


workflows:
    main:
      jobs:
      - build:
        context: SonarCloud


