version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    resource_class: medium
    environment:
      JVM_OPTS: -Xmx5000m
    steps:
      - checkout

      - run: sdkmanager --licenses
      - run: yes | sdkmanager --update || exit 0
      - run:
          command: ./gradlew androidDependencies
          when: always


      - run:
          name: Build apk
          command: |
            ./gradlew :app:assembleDebug
            ./gradlew :app:assembleDebugAndroidTest
      - store_artifacts:
          path: ./app/build/outputs/apk/debug/app-debug.apk
          destination: /apks/app-debug.apk

      #sonar cloud
      - run:
          name: Analyze on SonarCloud
          command: ./gradlew build sonarqube

